import { Catamaran } from "@next/font/google";
import Header from "./components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const catamaran = Catamaran({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={catamaran.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
